apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: pm25ml-large
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
            - image: europe-west1-docker.pkg.dev/vital-form-455413-p8/pm25ml/pm25ml:latest
              resources:
                limits:
                  cpu: 8000m
                  memory: 32Gi
              # Most of the env is defined in the workflow.yaml
              env:
                - name: EARTHDATA_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: EARTHDATA_USERNAME
                      key: latest
                - name: EARTHDATA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: EARTHDATA_PASSWORD
                      key: latest
          maxRetries: 0
          timeoutSeconds: "86400"
          serviceAccountName: pm25ml@vital-form-455413-p8.iam.gserviceaccount.com
